name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  # For PRs, later CI runs preempt previous ones. e.g. a force push on a PR
  # cancels running CI jobs and starts all new ones.
  #
  # For non-PR pushes, concurrency.group needs to be unique for every distinct
  # CI run we want to have happen. Use run_id, which in practice means all
  # non-PR CI runs are allowed to run without preempting each other.
  group: ${{ github.workflow }}-$${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.20"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Build ${{ matrix.go }}
        run: go build -v ./...

      - name: Test ${{ matrix.go }}
        run: go test -v -race ./...
